### PR TITLE
Fix Jacobian API for CasADi >= 3.6

### PR DESCRIPTION
**Pull request by hshose**
[Casadi #2178](https://github.com/casadi/casadi/issues/2178) broke the jacobian api.
I tried fixing this:
- [x] forward sensitivities
- [x] adjoint sensitivities
- [x]  hessian
- [x] `pendulum_test.py` for [forward and adjoint jacobians](https://github.com/FreyJo/casados-integrators/blob/main/examples/pendulum_tests.py#L96) succeeds
- [x] `pendulum_test.py` NLP test [with hessian](https://github.com/FreyJo/casados-integrators/blob/main/examples/pendulum_example.py#L337)
- [x] `pendulum_test.py` NLP test [without hessian](https://github.com/FreyJo/casados-integrators/blob/main/examples/pendulum_example.py#L333)

In both pendulum NLP tests (with / without Hessian), IPOPT converge to a different solution compared to the casadi integrators.
I'm a bit puzzled why, since the other tests seeem to run smoothly and I would expect at least the approximate Hessian case to work fine.

@FreyJo do you have an idea, what could be wrong there?
I'm sorry I didn't continue working on [your casadi3.6 branch](https://github.com/FreyJo/casados-integrators/tree/casadi3.6); I just found that branch when I created this PR :cry: 

I've tested this with Python 3.11, Casadi 3.6.5, acados commit [8d094a2](https://github.com/acados/acados/commit/8d094a21cb658a58f8acf8e27dd5ac7952d35e45).

### CODE REVIEW

**Comment by FreyJo** [comment]
Hi,

thanks a lot for the PR!
It looks very good! :+1: 
I just tried it out locally, and it also works on the NLP test with hessian.

I get:
```
test_ocp_nlp: error in X is 2.9943825197165097e-12.
test_ocp_nlp: error in U is 6.107114813858061e-11.
NLP solutions match wrt tol 2.0e-07.
test_ocp_nlp: SUCCESS!
```

Note that there is an issue with unloading the code generated library:
https://github.com/FreyJo/casados-integrators/blob/2cf3b3948bf7631d606999a4b7e922402f919298/examples/pendulum_tests.py#L99-L100
I added a note in https://github.com/FreyJo/casados-integrators/pull/4

Does it work for you if you don't run the other tests before?
I tested with casadi 3.6.5 and Python 3.10.

Overall, it seems that everything does work correctly now with CasADi >= 3.6.

Indeed most people are nowadays using CasADi >= 3.6. these days.
I would suggest to create a Release on the current `main` branch as the last version that is compatible `3.5.5` just before merging this one.
What do you think?

I just added a CasADi version check:
https://github.com/FreyJo/casados-integrators/blob/3815f81edc38e62586ad31ab8268c00bed8b59e3/casados_integrator.py#L34-L49
Could you modify that check on your PR?

Best,
Jonathan

**Comment by hshose** [comment]
Hi Jonathan,

thanks for the quick reply and nice, that the NLP example is working on your side.
I saw the note and just run the NLP problems. I.e., the `test_ocp_nlp(...)` function without previous calls to `test_forward_sim`, etc.

I get a result of:

```
Exception: results X have error 19.27672602822738. should be less than 2.0e-07
```

<details>
<summary>If I plot the results, for the casados integrator, I get something like this: (click for details)</summary>

image
... which looks like some local optimum to me.

</details>

<details>
<summary>For the casadi integrators, however, the solution looks fine to me: (click for details)</summary>

image

</details>

Maybe this is a weird artifact of my IPOPT version `3.14.11` with MUMPS `5.4.1`... What IPOPT version and linear solver are you running?


A release for Casadi 3.5.5 sounds good.
I have rebased my changes ontop the current main branch so you could merge them after that release, if you want.

I haven't tested any of the other examples (e.g., the `airborne_wind_energy_system/casados_simulation_test.py` loads some pickle that doesn't work with my changes to the Casados classes anymore).
I have added a warning to the README that some of the examples from your paper are not poerted to Casadi 3.6.x... Feel free to remove that if you don't like it :-) 

Best
Henrik

**Comment by FreyJo** [comment]
Hi Hendrik,

I remember, that I also had issues with converging to different local minima.
However, I am not able to reproduce the issue on your branch.
I just updated and tested again with exactly the versions you described: Python 3.11, IPOPT 3.14.11 with MUMPS 5.4.1.
I am a bit unsure what could be the issue then, maybe you can remove the generated.

> I haven't tested any of the other examples (e.g., the airborne_wind_energy_system/casados_simulation_test.py loads some pickle that doesn't work with my changes to the Casados classes anymore).

I also have some issues running this example with the new Python 3.11 environment.
For me, awebox installation seems to fail when installing scipy.

Since the integrator now works for me with all sensitivity modes and in an IPOPT NLP solver call, this can be merged IMO.

I will wait a bit more, if you maybe have a hint on the different behavior on your setup.

Best,
Jonathan

**Comment by hshose** [comment]
Wild :boar: removing all generated files, removing the virtual environment, and setting up everything from a scratch resolved the IPOPT convergence issue. I think I'll consider this problem an artifact of my messing around with CasADi versions in the process of figuring out how the callback / jacobian API changed. 

Thanks for your advice :heart:

**Comment by FreyJo** [comment]
Great that this fixed it!
Thanks a lot for the PR again :pray: 
I did some small modifications and will make a new release for CasADi 3.6 now!
I hope you can solver some NLPs with the `casados` integrator now :rocket:

**Pull request merged**
