### PR TITLE
add set_z_guess(), set_xdot_guess()

### PR DESCRIPTION
**Pull request by mohammed-hababeh**
- added z0 as a property to the CasadosIntegrator
 - set the z value of acados integrator in the eval function
 - used in the following way: casados_integrator.z0 = z #(numpy array of the initial guess)

### CODE REVIEW

**Comment by mohammed-hababeh** [comment]
Ran all examples again. They all still work.

**Comment by mohammed-hababeh** [comment]
After a quick discussion with @FreyJo, I decided to move the assignment of the z value of the integrator to the setter of the property. This way the value is only set in the initial call. The later calls could use the new z value that will be in memory. 

I also re-ran the examples again after the change and they all run.

**Review by FreyJo — COMMENTED** [review]
Looks good now!
Technically, we don't need `self._z0`, after our last discussion (i.e. setting it only once).
Maybe remove it, and the property and just do:
```
    def set_z_guess(self, value):
        '''
        Set initial guess of the algebraic variables to be used in the next call
        Parameters
        ----------
        value : np.ndarray
            value of the algebraic variables guess
        '''
        # set the value in the integrator to be used in the next call
        self.acados_integrator.set("z", value)
```
What do you think?

**Comment by mohammed-hababeh** [comment]
Thanks for the quick feedback. 

I also agree that it is irrelevant to the setting of the initial guess. However, the reason I kept it was that I saw you had variables for the state `self.x0` and control `self.z0`. Both of them are not used in the `eval` function. I am not familiar with the details of the code base, so I assumed you use these variables elsewhere. So I just wanted to stay consistent with the current code base. But if you don't see a need for a variable containing this initial guess, I will remove it and write the function as in your comment.

**Comment by FreyJo** [comment]
The reason for having `x0` and `u0` was that I attempted to make it faster in an OCP, by calculating all sensitivities, when there are new values for either of those, and only get the sensitivities when they are requested from the casadi NLP solver.
This extension didn't make it into the paper but the thoughts behind it are in Section III.E of the paper.
Now, it would be possible to also remove `x0`, `u0`.
But, they don't have the downside of outdating, which the z guess has, the way we agreed to implement it.

**Comment by mohammed-hababeh** [comment]
I understand. I have updated the code accordingly. And added initialization for `xdot` as well (in the same style). It might be relevant for some cases. Let me know if there is anything else I should add. 

I re-ran the examples again and also tested a model where I provided both `z_guess` and `xdot_guess` and it worked.

**Review by FreyJo — APPROVED** [review]
Great, thanks for the PR!

**Pull request merged**
